[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  pgbouncer/0 [executing] active: 
  pgbouncer/2 [executing] active: VIP: 10.102.217.67
  pgbouncer/3 [executing] active: 
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  pgbouncer/0 [executing] blocked: ha integration used without vip configuration
  pgbouncer/2 [executing] blocked: ha integration used without vip configuration
  pgbouncer/3 [executing] blocked: ha integration used without vip configuration
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  pgbouncer/2 [executing] blocked: ha integration used without vip configuration
  pgbouncer/3 [idle] blocked: ha integration used without vip configuration
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  pgbouncer/2 [idle] blocked: ha integration used without vip configuration
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  pgbouncer/0 [idle] blocked: ha integration used without vip configuration
  pgbouncer/2 [idle] blocked: ha integration used without vip configuration
  pgbouncer/3 [idle] blocked: ha integration used without vip configuration
[32mINFO    [0m integration.relations.pgbouncer_provider.test_data_integrator_ha:test_data_integrator_ha.py:150 Data integrator host is 10.102.217.237
[32mINFO    [0m pytest_operator.plugin:plugin.py:937 Model status:

Model    Controller     Cloud/Region         Version  SLA          Timestamp
testing  concierge-lxd  localhost/localhost  3.6.5    unsupported  01:58:00Z

App                       Version  Status  Scale  Charm                     Channel        Rev  Exposed  Message
data-integrator                    error       3  data-integrator           latest/edge    143  no       hook failed: "secret-changed"
hacluster                 2.1.2    active      3  hacluster                 2.4/stable     131  no       Unit is ready and clustered
pgbouncer                 1.21.0   active      3  pgbouncer                                  0  no       
postgresql                14.17    active      2  postgresql                14/edge        605  no       
self-signed-certificates           active      1  self-signed-certificates  latest/stable  264  no       

Unit                         Workload  Agent  Machine  Public address  Ports     Message
data-integrator/0*           active    idle   0        10.102.217.66             
  hacluster/0*               active    idle            10.102.217.66             Unit is ready and clustered
  pgbouncer/3                active    idle            10.102.217.66   6432/tcp  
data-integrator/1            error     idle   1        10.102.217.99             hook failed: "secret-changed"
  hacluster/1                active    idle            10.102.217.99             Unit is ready and clustered
  pgbouncer/0                active    idle            10.102.217.99   6432/tcp  
data-integrator/2            error     idle   2        10.102.217.237            hook failed: "secret-changed"
  hacluster/2                active    idle            10.102.217.237            Unit is ready and clustered
  pgbouncer/2*               active    idle            10.102.217.237  6432/tcp  
postgresql/0*                active    idle   4        10.102.217.17   5432/tcp  Primary
postgresql/1                 active    idle   5        10.102.217.88   5432/tcp  
self-signed-certificates/0*  active    idle   3        10.102.217.100            

Machine  State    Address         Inst id        Base          AZ  Message
0        started  10.102.217.66   juju-37548a-0  ubuntu@22.04      Running
1        started  10.102.217.99   juju-37548a-1  ubuntu@22.04      Running
2        started  10.102.217.237  juju-37548a-2  ubuntu@22.04      Running
3        started  10.102.217.100  juju-37548a-3  ubuntu@22.04      Running
4        started  10.102.217.17   juju-37548a-4  ubuntu@22.04      Running
5        started  10.102.217.88   juju-37548a-5  ubuntu@22.04      Running

[32mINFO    [0m pytest_operator.plugin:plugin.py:943 Juju error logs:

machine-0: 01:42:39 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-0: 01:42:39 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-data-integrator-0: 01:42:39 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-1: 01:45:27 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-1: 01:45:27 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-data-integrator-1: 01:45:28 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-hacluster-1: 01:45:32 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-4: 01:45:47 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-4: 01:45:47 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-postgresql-0: 01:45:47 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-2: 01:46:11 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-2: 01:46:11 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-data-integrator-2: 01:46:11 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-hacluster-2: 01:46:15 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-5: 01:46:42 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-5: 01:46:42 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-postgresql-1: 01:46:42 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-3: 01:47:04 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-3: 01:47:04 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-self-signed-certificates-0: 01:47:04 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-postgresql-0: 01:47:14 ERROR unit.postgresql/0.juju-log Unable to get the state of the cluster
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/lib/python3.10/site-packages/urllib3/connection.py", line 198, in _new_conn
    sock = connection.create_connection(
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/lib/python3.10/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 493, in _make_request
    conn.request(
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/lib/python3.10/site-packages/urllib3/connection.py", line 445, in request
    self.endheaders()
  File "/usr/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/usr/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/lib/python3.10/site-packages/urllib3/connection.py", line 276, in connect
    self.sock = self._new_conn()
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/lib/python3.10/site-packages/urllib3/connection.py", line 213, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fbd195a53f0>: Failed to establish a new connection: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/lib/python3.10/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 841, in urlopen
    retries = retries.increment(
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/lib/python3.10/site-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='10.102.217.17', port=8008): Max retries exceeded with url: /cluster (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbd195a53f0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-0/charm/src/cluster.py", line 563, in are_replicas_up
    response = requests.get(
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/lib/python3.10/site-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='10.102.217.17', port=8008): Max retries exceeded with url: /cluster (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbd195a53f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-pgbouncer-0: 01:51:14 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-pgbouncer-2: 01:51:14 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-pgbouncer-3: 01:51:14 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-data-integrator-2: 01:56:05 ERROR unit.data-integrator/2.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-data-integrator-2/charm/src/charm.py", line 516, in <module>
    main(IntegratorCharm)
  File "/var/lib/juju/agents/unit-data-integrator-2/charm/venv/lib/python3.10/site-packages/ops/__init__.py", line 347, in __call__
    return _main.main(charm_class=charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-data-integrator-2/charm/venv/lib/python3.10/site-packages/ops/_main.py", line 565, in main
    manager.run()
  File "/var/lib/juju/agents/unit-data-integrator-2/charm/venv/lib/python3.10/site-packages/ops/_main.py", line 550, in run
    self._emit()
  File "/var/lib/juju/agents/unit-data-integrator-2/charm/venv/lib/python3.10/site-packages/ops/_main.py", line 502, in _emit
    self._emit_charm_event(self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-data-integrator-2/charm/venv/lib/python3.10/site-packages/ops/_main.py", line 537, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-data-integrator-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-data-integrator-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 907, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-data-integrator-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 997, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-data-integrator-2/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 4108, in _on_secret_changed_event
    getattr(self.on, "etcd_ready").emit(relation, app=relation.app, unit=remote_unit)
  File "/var/lib/juju/agents/unit-data-integrator-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-data-integrator-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 907, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-data-integrator-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 997, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-data-integrator-2/charm/src/charm.py", line 301, in _on_etcd_ready
    self._update_relation_status(event, Statuses.ACTIVE.name)
  File "/var/lib/juju/agents/unit-data-integrator-2/charm/src/charm.py", line 305, in _update_relation_status
    self.set_secret("app", event.relation.name, status)
  File "/var/lib/juju/agents/unit-data-integrator-2/charm/src/charm.py", line 510, in set_secret
    self.app_peer_data.update({key: value})
  File "/var/lib/juju/agents/unit-data-integrator-2/charm/venv/lib/python3.10/site-packages/ops/model.py", line 1986, in update
    self._validate_write(changes)  # always check permissions
  File "/var/lib/juju/agents/unit-data-integrator-2/charm/venv/lib/python3.10/site-packages/ops/model.py", line 1903, in _validate_write
    self._validate_write_access()
  File "/var/lib/juju/agents/unit-data-integrator-2/charm/venv/lib/python3.10/site-packages/ops/model.py", line 1931, in _validate_write_access
    raise RelationDataAccessError(
ops.model.RelationDataAccessError: data-integrator/2 is not leader and cannot write application data.
unit-data-integrator-2: 01:56:05 ERROR juju.worker.uniter.operation hook "secret-changed" (via hook dispatching script: dispatch) failed: exit status 1
unit-data-integrator-1: 01:56:08 ERROR unit.data-integrator/1.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-data-integrator-1/charm/src/charm.py", line 516, in <module>
    main(IntegratorCharm)
  File "/var/lib/juju/agents/unit-data-integrator-1/charm/venv/lib/python3.10/site-packages/ops/__init__.py", line 347, in __call__
    return _main.main(charm_class=charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-data-integrator-1/charm/venv/lib/python3.10/site-packages/ops/_main.py", line 565, in main
    manager.run()
  File "/var/lib/juju/agents/unit-data-integrator-1/charm/venv/lib/python3.10/site-packages/ops/_main.py", line 550, in run
    self._emit()
  File "/var/lib/juju/agents/unit-data-integrator-1/charm/venv/lib/python3.10/site-packages/ops/_main.py", line 502, in _emit
    self._emit_charm_event(self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-data-integrator-1/charm/venv/lib/python3.10/site-packages/ops/_main.py", line 537, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-data-integrator-1/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-data-integrator-1/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 907, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-data-integrator-1/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 997, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-data-integrator-1/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 4108, in _on_secret_changed_event
    getattr(self.on, "etcd_ready").emit(relation, app=relation.app, unit=remote_unit)
  File "/var/lib/juju/agents/unit-data-integrator-1/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-data-integrator-1/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 907, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-data-integrator-1/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 997, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-data-integrator-1/charm/src/charm.py", line 301, in _on_etcd_ready
    self._update_relation_status(event, Statuses.ACTIVE.name)
  File "/var/lib/juju/agents/unit-data-integrator-1/charm/src/charm.py", line 305, in _update_relation_status
    self.set_secret("app", event.relation.name, status)
  File "/var/lib/juju/agents/unit-data-integrator-1/charm/src/charm.py", line 510, in set_secret
    self.app_peer_data.update({key: value})
  File "/var/lib/juju/agents/unit-data-integrator-1/charm/venv/lib/python3.10/site-packages/ops/model.py", line 1986, in update
    self._validate_write(changes)  # always check permissions
  File "/var/lib/juju/agents/unit-data-integrator-1/charm/venv/lib/python3.10/site-packages/ops/model.py", line 1903, in _validate_write
    self._validate_write_access()
  File "/var/lib/juju/agents/unit-data-integrator-1/charm/venv/lib/python3.10/site-packages/ops/model.py", line 1931, in _validate_write_access
    raise RelationDataAccessError(
ops.model.RelationDataAccessError: data-integrator/1 is not leader and cannot write application data.
unit-data-integrator-1: 01:56:09 ERROR juju.worker.uniter.operation hook "secret-changed" (via hook dispatching script: dispatch) failed: exit status 1
unit-data-integrator-2: 01:56:17 ERROR unit.data-integrator/2.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-data-integrator-2/charm/src/charm.py", line 516, in <module>
    main(IntegratorCharm)
  File "/var/lib/juju/agents/unit-data-integrator-2/charm/venv/lib/python3.10/site-packages/ops/__init__.py", line 347, in __call__
    return _main.main(charm_class=charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-data-integrator-2/charm/venv/lib/python3.10/site-packages/ops/_main.py", line 565, in main
    manager.run()
  File "/var/lib/juju/agents/unit-data-integrator-2/charm/venv/lib/python3.10/site-packages/ops/_main.py", line 550, in run
    self._emit()
  File "/var/lib/juju/agents/unit-data-integrator-2/charm/venv/lib/python3.10/site-packages/ops/_main.py", line 502, in _emit
    self._emit_charm_event(self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-data-integrator-2/charm/venv/lib/python3.10/site-packages/ops/_main.py", line 537, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-data-integrator-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-data-integrator-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 907, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-data-integrator-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 997, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-data-integrator-2/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 4108, in _on_secret_changed_event
    getattr(self.on, "etcd_ready").emit(relation, app=relation.app, unit=remote_unit)
  File "/var/lib/juju/agents/unit-data-integrator-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-data-integrator-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 907, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-data-integrator-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 997, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-data-integrator-2/charm/src/charm.py", line 301, in _on_etcd_ready
    self._update_relation_status(event, Statuses.ACTIVE.name)
  File "/var/lib/juju/agents/unit-data-integrator-2/charm/src/charm.py", line 305, in _update_relation_status
    self.set_secret("app", event.relation.name, status)
  File "/var/lib/juju/agents/unit-data-integrator-2/charm/src/charm.py", line 510, in set_secret
    self.app_peer_data.update({key: value})
  File "/var/lib/juju/agents/unit-data-integrator-2/charm/venv/lib/python3.10/site-packages/ops/model.py", line 1986, in update
    self._validate_write(changes)  # always check permissions
  File "/var/lib/juju/agents/unit-data-integrator-2/charm/venv/lib/python3.10/site-packages/ops/model.py", line 1903, in _validate_write
    self._validate_write_access()
  File "/var/lib/juju/agents/unit-data-integrator-2/charm/venv/lib/python3.10/site-packages/ops/model.py", line 1931, in _validate_write_access
    raise RelationDataAccessError(
ops.model.RelationDataAccessError: data-integrator/2 is not leader and cannot write application data.
unit-data-integrator-2: 01:56:18 ERROR juju.worker.uniter.operation hook "secret-changed" (via hook dispatching script: dispatch) failed: exit status 1
unit-data-integrator-1: 01:56:19 ERROR unit.data-integrator/1.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-data-integrator-1/charm/src/charm.py", line 516, in <module>
    main(IntegratorCharm)
  File "/var/lib/juju/agents/unit-data-integrator-1/charm/venv/lib/python3.10/site-packages/ops/__init__.py", line 347, in __call__
    return _main.main(charm_class=charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-data-integrator-1/charm/venv/lib/python3.10/site-packages/ops/_main.py", line 565, in main
    manager.run()
  File "/var/lib/juju/agents/unit-data-integrator-1/charm/venv/lib/python3.10/site-packages/ops/_main.py", line 550, in run
    self._emit()
  File "/var/lib/juju/agents/unit-data-integrator-1/charm/venv/lib/python3.10/site-packages/ops/_main.py", line 502, in _emit
    self._emit_charm_event(self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-data-integrator-1/charm/venv/lib/python3.10/site-packages/ops/_main.py", line 537, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-data-integrator-1/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-data-integrator-1/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 907, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-data-integrator-1/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 997, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-data-integrator-1/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 4108, in _on_secret_changed_event
    getattr(self.on, "etcd_ready").emit(relation, app=relation.app, unit=remote_unit)
  File "/var/lib/juju/agents/unit-data-integrator-1/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-data-integrator-1/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 907, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-data-integrator-1/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 997, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-data-integrator-1/charm/src/charm.py", line 301, in _on_etcd_ready
    self._update_relation_status(event, Statuses.ACTIVE.name)
  File "/var/lib/juju/agents/unit-data-integrator-1/charm/src/charm.py", line 305, in _update_relation_status
    self.set_secret("app", event.relation.name, status)
  File "/var/lib/juju/agents/unit-data-integrator-1/charm/src/charm.py", line 510, in set_secret
    self.app_peer_data.update({key: value})
  File "/var/lib/juju/agents/unit-data-integrator-1/charm/venv/lib/python3.10/site-packages/ops/model.py", line 1986, in update
    self._validate_write(changes)  # always check permissions
  File "/var/lib/juju/agents/unit-data-integrator-1/charm/venv/lib/python3.10/site-packages/ops/model.py", line 1903, in _validate_write
    self._validate_write_access()
  File "/var/lib/juju/agents/unit-data-integrator-1/charm/venv/lib/python3.10/site-packages/ops/model.py", line 1931, in _validate_write_access
    raise RelationDataAccessError(
ops.model.RelationDataAccessError: data-integrator/1 is not leader and cannot write application data.
unit-data-integrator-1: 01:56:19 ERROR juju.worker.uniter.operation hook "secret-changed" (via hook dispatching script: dispatch) failed: exit status 1
unit-data-integrator-2: 01:56:28 ERROR unit.data-integrator/2.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-data-integrator-2/charm/src/charm.py", line 516, in <module>
    main(IntegratorCharm)
  File "/var/lib/juju/agents/unit-data-integrator-2/charm/venv/lib/python3.10/site-packages/ops/__init__.py", line 347, in __call__
    return _main.main(charm_class=charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-data-integrator-2/charm/venv/lib/python3.10/site-packages/ops/_main.py", line 565, in main
    manager.run()
  File "/var/lib/juju/agents/unit-data-integrator-2/charm/venv/lib/python3.10/site-packages/ops/_main.py", line 550, in run
    self._emit()
  File "/var/lib/juju/agents/unit-data-integrator-2/charm/venv/lib/python3.10/site-packages/ops/_main.py", line 502, in _emit
    self._emit_charm_event(self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-data-integrator-2/charm/venv/lib/python3.10/site-packages/ops/_main.py", line 537, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-data-integrator-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-data-integrator-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 907, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-data-integrator-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 997, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-data-integrator-2/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 4108, in _on_secret_changed_event
    getattr(self.on, "etcd_ready").emit(relation, app=relation.app, unit=remote_unit)
  File "/var/lib/juju/agents/unit-data-integrator-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-data-integrator-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 907, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-data-integrator-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 997, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-data-integrator-2/charm/src/charm.py", line 301, in _on_etcd_ready
    self._update_relation_status(event, Statuses.ACTIVE.name)
  File "/var/lib/juju/agents/unit-data-integrator-2/charm/src/charm.py", line 305, in _update_relation_status
    self.set_secret("app", event.relation.name, status)
  File "/var/lib/juju/agents/unit-data-integrator-2/charm/src/charm.py", line 510, in set_secret
    self.app_peer_data.update({key: value})
  File "/var/lib/juju/agents/unit-data-integrator-2/charm/venv/lib/python3.10/site-packages/ops/model.py", line 1986, in update
    self._validate_write(changes)  # always check permissions
  File "/var/lib/juju/agents/unit-data-integrator-2/charm/venv/lib/python3.10/site-packages/ops/model.py", line 1903, in _validate_write
    self._validate_write_access()
  File "/var/lib/juju/agents/unit-data-integrator-2/charm/venv/lib/python3.10/site-packages/ops/model.py", line 1931, in _validate_write_access
    raise RelationDataAccessError(
ops.model.RelationDataAccessError: data-integrator/2 is not leader and cannot write application data.
unit-data-integrator-2: 01:56:28 ERROR juju.worker.uniter.operation hook "secret-changed" (via hook dispatching script: dispatch) failed: exit status 1
unit-data-integrator-1: 01:56:34 ERROR unit.data-integrator/1.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-data-integrator-1/charm/src/charm.py", line 516, in <module>
    main(IntegratorCharm)
  File "/var/lib/juju/agents/unit-data-integrator-1/charm/venv/lib/python3.10/site-packages/ops/__init__.py", line 347, in __call__
    return _main.main(charm_class=charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-data-integrator-1/charm/venv/lib/python3.10/site-packages/ops/_main.py", line 565, in main
    manager.run()
  File "/var/lib/juju/agents/unit-data-integrator-1/charm/venv/lib/python3.10/site-packages/ops/_main.py", line 550, in run
    self._emit()
  File "/var/lib/juju/agents/unit-data-integrator-1/charm/venv/lib/python3.10/site-packages/ops/_main.py", line 502, in _emit
    self._emit_charm_event(self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-data-integrator-1/charm/venv/lib/python3.10/site-packages/ops/_main.py", line 537, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-data-integrator-1/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-data-integrator-1/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 907, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-data-integrator-1/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 997, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-data-integrator-1/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 4108, in _on_secret_changed_event
    getattr(self.on, "etcd_ready").emit(relation, app=relation.app, unit=remote_unit)
  File "/var/lib/juju/agents/unit-data-integrator-1/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-data-integrator-1/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 907, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-data-integrator-1/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 997, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-data-integrator-1/charm/src/charm.py", line 301, in _on_etcd_ready
    self._update_relation_status(event, Statuses.ACTIVE.name)
  File "/var/lib/juju/agents/unit-data-integrator-1/charm/src/charm.py", line 305, in _update_relation_status
    self.set_secret("app", event.relation.name, status)
  File "/var/lib/juju/agents/unit-data-integrator-1/charm/src/charm.py", line 510, in set_secret
    self.app_peer_data.update({key: value})
  File "/var/lib/juju/agents/unit-data-integrator-1/charm/venv/lib/python3.10/site-packages/ops/model.py", line 1986, in update
    self._validate_write(changes)  # always check permissions
  File "/var/lib/juju/agents/unit-data-integrator-1/charm/venv/lib/python3.10/site-packages/ops/model.py", line 1903, in _validate_write
    self._validate_write_access()
  File "/var/lib/juju/agents/unit-data-integrator-1/charm/venv/lib/python3.10/site-packages/ops/model.py", line 1931, in _validate_write_access
    raise RelationDataAccessError(
ops.model.RelationDataAccessError: data-integrator/1 is not leader and cannot write application data.
unit-data-integrator-1: 01:56:34 ERROR juju.worker.uniter.operation hook "secret-changed" (via hook dispatching script: dispatch) failed: exit status 1
unit-data-integrator-2: 01:56:52 ERROR unit.data-integrator/2.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-data-integrator-2/charm/src/charm.py", line 516, in <module>
    main(IntegratorCharm)
  File "/var/lib/juju/agents/unit-data-integrator-2/charm/venv/lib/python3.10/site-packages/ops/__init__.py", line 347, in __call__
    return _main.main(charm_class=charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-data-integrator-2/charm/venv/lib/python3.10/site-packages/ops/_main.py", line 565, in main
    manager.run()
  File "/var/lib/juju/agents/unit-data-integrator-2/charm/venv/lib/python3.10/site-packages/ops/_main.py", line 550, in run
    self._emit()
  File "/var/lib/juju/agents/unit-data-integrator-2/charm/venv/lib/python3.10/site-packages/ops/_main.py", line 502, in _emit
    self._emit_charm_event(self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-data-integrator-2/charm/venv/lib/python3.10/site-packages/ops/_main.py", line 537, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-data-integrator-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-data-integrator-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 907, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-data-integrator-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 997, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-data-integrator-2/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 4108, in _on_secret_changed_event
    getattr(self.on, "etcd_ready").emit(relation, app=relation.app, unit=remote_unit)
  File "/var/lib/juju/agents/unit-data-integrator-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-data-integrator-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 907, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-data-integrator-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 997, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-data-integrator-2/charm/src/charm.py", line 301, in _on_etcd_ready
    self._update_relation_status(event, Statuses.ACTIVE.name)
  File "/var/lib/juju/agents/unit-data-integrator-2/charm/src/charm.py", line 305, in _update_relation_status
    self.set_secret("app", event.relation.name, status)
  File "/var/lib/juju/agents/unit-data-integrator-2/charm/src/charm.py", line 510, in set_secret
    self.app_peer_data.update({key: value})
  File "/var/lib/juju/agents/unit-data-integrator-2/charm/venv/lib/python3.10/site-packages/ops/model.py", line 1986, in update
    self._validate_write(changes)  # always check permissions
  File "/var/lib/juju/agents/unit-data-integrator-2/charm/venv/lib/python3.10/site-packages/ops/model.py", line 1903, in _validate_write
    self._validate_write_access()
  File "/var/lib/juju/agents/unit-data-integrator-2/charm/venv/lib/python3.10/site-packages/ops/model.py", line 1931, in _validate_write_access
    raise RelationDataAccessError(
ops.model.RelationDataAccessError: data-integrator/2 is not leader and cannot write application data.
unit-data-integrator-2: 01:56:52 ERROR juju.worker.uniter.operation hook "secret-changed" (via hook dispatching script: dispatch) failed: exit status 1
unit-data-integrator-1: 01:56:55 ERROR unit.data-integrator/1.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-data-integrator-1/charm/src/charm.py", line 516, in <module>
    main(IntegratorCharm)
  File "/var/lib/juju/agents/unit-data-integrator-1/charm/venv/lib/python3.10/site-packages/ops/__init__.py", line 347, in __call__
    return _main.main(charm_class=charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-data-integrator-1/charm/venv/lib/python3.10/site-packages/ops/_main.py", line 565, in main
    manager.run()
  File "/var/lib/juju/agents/unit-data-integrator-1/charm/venv/lib/python3.10/site-packages/ops/_main.py", line 550, in run
    self._emit()
  File "/var/lib/juju/agents/unit-data-integrator-1/charm/venv/lib/python3.10/site-packages/ops/_main.py", line 502, in _emit
    self._emit_charm_event(self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-data-integrator-1/charm/venv/lib/python3.10/site-packages/ops/_main.py", line 537, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-data-integrator-1/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-data-integrator-1/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 907, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-data-integrator-1/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 997, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-data-integrator-1/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 4108, in _on_secret_changed_event
    getattr(self.on, "etcd_ready").emit(relation, app=relation.app, unit=remote_unit)
  File "/var/lib/juju/agents/unit-data-integrator-1/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-data-integrator-1/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 907, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-data-integrator-1/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 997, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-data-integrator-1/charm/src/charm.py", line 301, in _on_etcd_ready
    self._update_relation_status(event, Statuses.ACTIVE.name)
  File "/var/lib/juju/agents/unit-data-integrator-1/charm/src/charm.py", line 305, in _update_relation_status
    self.set_secret("app", event.relation.name, status)
  File "/var/lib/juju/agents/unit-data-integrator-1/charm/src/charm.py", line 510, in set_secret
    self.app_peer_data.update({key: value})
  File "/var/lib/juju/agents/unit-data-integrator-1/charm/venv/lib/python3.10/site-packages/ops/model.py", line 1986, in update
    self._validate_write(changes)  # always check permissions
  File "/var/lib/juju/agents/unit-data-integrator-1/charm/venv/lib/python3.10/site-packages/ops/model.py", line 1903, in _validate_write
    self._validate_write_access()
  File "/var/lib/juju/agents/unit-data-integrator-1/charm/venv/lib/python3.10/site-packages/ops/model.py", line 1931, in _validate_write_access
    raise RelationDataAccessError(
ops.model.RelationDataAccessError: data-integrator/1 is not leader and cannot write application data.
unit-data-integrator-1: 01:56:56 ERROR juju.worker.uniter.operation hook "secret-changed" (via hook dispatching script: dispatch) failed: exit status 1
unit-data-integrator-2: 01:57:30 ERROR unit.data-integrator/2.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-data-integrator-2/charm/src/charm.py", line 516, in <module>
    main(IntegratorCharm)
  File "/var/lib/juju/agents/unit-data-integrator-2/charm/venv/lib/python3.10/site-packages/ops/__init__.py", line 347, in __call__
    return _main.main(charm_class=charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-data-integrator-2/charm/venv/lib/python3.10/site-packages/ops/_main.py", line 565, in main
    manager.run()
  File "/var/lib/juju/agents/unit-data-integrator-2/charm/venv/lib/python3.10/site-packages/ops/_main.py", line 550, in run
    self._emit()
  File "/var/lib/juju/agents/unit-data-integrator-2/charm/venv/lib/python3.10/site-packages/ops/_main.py", line 502, in _emit
    self._emit_charm_event(self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-data-integrator-2/charm/venv/lib/python3.10/site-packages/ops/_main.py", line 537, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-data-integrator-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-data-integrator-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 907, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-data-integrator-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 997, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-data-integrator-2/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 4108, in _on_secret_changed_event
    getattr(self.on, "etcd_ready").emit(relation, app=relation.app, unit=remote_unit)
  File "/var/lib/juju/agents/unit-data-integrator-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-data-integrator-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 907, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-data-integrator-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 997, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-data-integrator-2/charm/src/charm.py", line 301, in _on_etcd_ready
    self._update_relation_status(event, Statuses.ACTIVE.name)
  File "/var/lib/juju/agents/unit-data-integrator-2/charm/src/charm.py", line 305, in _update_relation_status
    self.set_secret("app", event.relation.name, status)
  File "/var/lib/juju/agents/unit-data-integrator-2/charm/src/charm.py", line 510, in set_secret
    self.app_peer_data.update({key: value})
  File "/var/lib/juju/agents/unit-data-integrator-2/charm/venv/lib/python3.10/site-packages/ops/model.py", line 1986, in update
    self._validate_write(changes)  # always check permissions
  File "/var/lib/juju/agents/unit-data-integrator-2/charm/venv/lib/python3.10/site-packages/ops/model.py", line 1903, in _validate_write
    self._validate_write_access()
  File "/var/lib/juju/agents/unit-data-integrator-2/charm/venv/lib/python3.10/site-packages/ops/model.py", line 1931, in _validate_write_access
    raise RelationDataAccessError(
ops.model.RelationDataAccessError: data-integrator/2 is not leader and cannot write application data.
unit-data-integrator-2: 01:57:30 ERROR juju.worker.uniter.operation hook "secret-changed" (via hook dispatching script: dispatch) failed: exit status 1
unit-data-integrator-1: 01:57:37 ERROR unit.data-integrator/1.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-data-integrator-1/charm/src/charm.py", line 516, in <module>
    main(IntegratorCharm)
  File "/var/lib/juju/agents/unit-data-integrator-1/charm/venv/lib/python3.10/site-packages/ops/__init__.py", line 347, in __call__
    return _main.main(charm_class=charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-data-integrator-1/charm/venv/lib/python3.10/site-packages/ops/_main.py", line 565, in main
    manager.run()
  File "/var/lib/juju/agents/unit-data-integrator-1/charm/venv/lib/python3.10/site-packages/ops/_main.py", line 550, in run
    self._emit()
  File "/var/lib/juju/agents/unit-data-integrator-1/charm/venv/lib/python3.10/site-packages/ops/_main.py", line 502, in _emit
    self._emit_charm_event(self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-data-integrator-1/charm/venv/lib/python3.10/site-packages/ops/_main.py", line 537, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-data-integrator-1/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-data-integrator-1/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 907, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-data-integrator-1/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 997, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-data-integrator-1/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 4108, in _on_secret_changed_event
    getattr(self.on, "etcd_ready").emit(relation, app=relation.app, unit=remote_unit)
  File "/var/lib/juju/agents/unit-data-integrator-1/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-data-integrator-1/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 907, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-data-integrator-1/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 997, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-data-integrator-1/charm/src/charm.py", line 301, in _on_etcd_ready
    self._update_relation_status(event, Statuses.ACTIVE.name)
  File "/var/lib/juju/agents/unit-data-integrator-1/charm/src/charm.py", line 305, in _update_relation_status
    self.set_secret("app", event.relation.name, status)
  File "/var/lib/juju/agents/unit-data-integrator-1/charm/src/charm.py", line 510, in set_secret
    self.app_peer_data.update({key: value})
  File "/var/lib/juju/agents/unit-data-integrator-1/charm/venv/lib/python3.10/site-packages/ops/model.py", line 1986, in update
    self._validate_write(changes)  # always check permissions
  File "/var/lib/juju/agents/unit-data-integrator-1/charm/venv/lib/python3.10/site-packages/ops/model.py", line 1903, in _validate_write
    self._validate_write_access()
  File "/var/lib/juju/agents/unit-data-integrator-1/charm/venv/lib/python3.10/site-packages/ops/model.py", line 1931, in _validate_write_access
    raise RelationDataAccessError(
ops.model.RelationDataAccessError: data-integrator/1 is not leader and cannot write application data.
unit-data-integrator-1: 01:57:37 ERROR juju.worker.uniter.operation hook "secret-changed" (via hook dispatching script: dispatch) failed: exit status 1

[32mINFO    [0m pytest_operator.plugin:plugin.py:1025 Forgetting model main...