[32mINFO    [0m pytest_operator.plugin:plugin.py:951 Model status:

Model    Controller     Cloud/Region         Version  SLA          Timestamp
testing  concierge-lxd  localhost/localhost  3.6.10   unsupported  01:52:13Z

App                  Version  Status   Scale  Charm                Channel      Rev  Exposed  Message
pgbouncer            1.21.0   error        1  pgbouncer                           0  no       hook failed: "backend-database-relation-changed"
postgresql           14.19    active       1  postgresql           14/edge      918  no       
postgresql-test-app           blocked      1  postgresql-test-app  latest/edge  406  no       No database integration available

Unit                    Workload  Agent      Machine  Public address  Ports     Message
postgresql-test-app/0*  blocked   idle       0        10.231.199.136            No database integration available
  pgbouncer/0*          error     idle                10.231.199.136            hook failed: "backend-database-relation-changed"
postgresql/0*           active    executing  1        10.231.199.130  5432/tcp  Primary

Machine  State    Address         Inst id        Base          AZ             Message
0        started  10.231.199.136  juju-35144b-0  ubuntu@22.04  runnervm3ublj  Running
1        started  10.231.199.130  juju-35144b-1  ubuntu@22.04  runnervm3ublj  Running

[32mINFO    [0m pytest_operator.plugin:plugin.py:957 Juju error logs:

machine-0: 01:50:12 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-0: 01:50:12 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-1: 01:51:03 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-1: 01:51:03 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-postgresql-0: 01:51:46 ERROR unit.postgresql/0.juju-log Failed to list PostgreSQL database users: could not translate host name "None" to address: Temporary failure in name resolution

unit-pgbouncer-0: 01:52:12 ERROR unit.pgbouncer/0.juju-log backend-database:7: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-pgbouncer-0/charm/src/charm.py", line 1024, in <module>
    main(PgBouncerCharm)
  File "/var/lib/juju/agents/unit-pgbouncer-0/charm/venv/lib/python3.10/site-packages/ops/__init__.py", line 356, in __call__
    return _main.main(charm_class=charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-pgbouncer-0/charm/venv/lib/python3.10/site-packages/ops/_main.py", line 502, in main
    manager.run()
  File "/var/lib/juju/agents/unit-pgbouncer-0/charm/venv/lib/python3.10/site-packages/ops/_main.py", line 486, in run
    self._emit()
  File "/var/lib/juju/agents/unit-pgbouncer-0/charm/venv/lib/python3.10/site-packages/ops/_main.py", line 421, in _emit
    self._emit_charm_event(self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-pgbouncer-0/charm/venv/lib/python3.10/site-packages/ops/_main.py", line 465, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-pgbouncer-0/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 351, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-pgbouncer-0/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 924, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-pgbouncer-0/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 1030, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-pgbouncer-0/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 3625, in _on_relation_changed_event
    getattr(self.on, "database_created").emit(
  File "/var/lib/juju/agents/unit-pgbouncer-0/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 351, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-pgbouncer-0/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 924, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-pgbouncer-0/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 1030, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-pgbouncer-0/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 1146, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-pgbouncer-0/charm/src/relations/backend_database.py", line 240, in _on_database_created
    self.initialise_auth_function(self.collect_databases())
  File "/var/lib/juju/agents/unit-pgbouncer-0/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 1146, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-pgbouncer-0/charm/src/relations/backend_database.py", line 376, in initialise_auth_function
    with self.postgres._connect_to_database(dbname) as conn, conn.cursor() as cursor:
  File "/var/lib/juju/agents/unit-pgbouncer-0/charm/lib/charms/postgresql_k8s/v0/postgresql.py", line 184, in _connect_to_database
    connection = psycopg2.connect(
  File "/var/lib/juju/agents/unit-pgbouncer-0/charm/venv/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "10.231.199.130", port 5432 failed: FATAL:  no pg_hba.conf entry for host "10.231.199.136", user "relation-7", database "postgres", no encryption

unit-pgbouncer-0: 01:52:12 ERROR juju.worker.uniter.operation hook "backend-database-relation-changed" (via hook dispatching script: dispatch) failed: exit status 1

[32mINFO    [0m pytest_operator.plugin:plugin.py:1039 Forgetting model main...