[32mINFO    [0m pytest_operator.plugin:plugin.py:929 Model status:

Model  Controller           Cloud/Region         Version  SLA          Timestamp
test   localhost-localhost  localhost/localhost  3.4.6    unsupported  01:53:45Z

App                  Version  Status  Scale  Charm                Channel      Rev  Exposed  Message
pgbouncer            1.21.0   error       3  pgbouncer                           0  no       hook failed: "backend-database-relation-changed"
postgresql           14.13    active      3  postgresql           14/edge      532  no       
postgresql-test-app           active      3  postgresql-test-app  latest/edge  299  no       

Unit                    Workload  Agent      Machine  Public address  Ports     Message
postgresql-test-app/0*  active    executing  0        10.120.111.149            
  pgbouncer/0*          active    executing           10.120.111.149            
postgresql-test-app/1   active    idle       1        10.120.111.229            
  pgbouncer/1           error     idle                10.120.111.229            hook failed: "backend-database-relation-changed"
postgresql-test-app/2   active    idle       2        10.120.111.86             
  pgbouncer/2           blocked   executing           10.120.111.86             PgBouncer service pgbouncer-pgbouncer-prometheus not running
postgresql/0            active    executing  3        10.120.111.193  5432/tcp  
postgresql/1            active    executing  4        10.120.111.188  5432/tcp  
postgresql/2*           active    executing  5        10.120.111.230  5432/tcp  Primary

Machine  State    Address         Inst id        Base          AZ  Message
0        started  10.120.111.149  juju-a641e0-0  ubuntu@22.04      Running
1        started  10.120.111.229  juju-a641e0-1  ubuntu@22.04      Running
2        started  10.120.111.86   juju-a641e0-2  ubuntu@22.04      Running
3        started  10.120.111.193  juju-a641e0-3  ubuntu@22.04      Running
4        started  10.120.111.188  juju-a641e0-4  ubuntu@22.04      Running
5        started  10.120.111.230  juju-a641e0-5  ubuntu@22.04      Running

[32mINFO    [0m pytest_operator.plugin:plugin.py:935 Juju error logs:

machine-0: 01:41:18 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-0: 01:41:18 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-postgresql-test-app-0: 01:41:18 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-1: 01:41:19 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-1: 01:41:19 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-postgresql-test-app-1: 01:41:20 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-2: 01:41:23 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-2: 01:41:23 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-pgbouncer-0: 01:41:24 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-postgresql-test-app-2: 01:41:24 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-pgbouncer-1: 01:41:25 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-pgbouncer-2: 01:41:29 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-5: 01:45:48 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-5: 01:45:48 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-postgresql-2: 01:45:48 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-4: 01:45:49 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-4: 01:45:49 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-postgresql-1: 01:45:49 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-3: 01:45:50 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-3: 01:45:50 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-postgresql-0: 01:45:51 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-postgresql-2: 01:47:06 ERROR unit.postgresql/2.juju-log Unable to get the state of the cluster
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-2/charm/venv/urllib3/connection.py", line 199, in _new_conn
    sock = connection.create_connection(
  File "/var/lib/juju/agents/unit-postgresql-2/charm/venv/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/var/lib/juju/agents/unit-postgresql-2/charm/venv/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-2/charm/venv/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
  File "/var/lib/juju/agents/unit-postgresql-2/charm/venv/urllib3/connectionpool.py", line 495, in _make_request
    conn.request(
  File "/var/lib/juju/agents/unit-postgresql-2/charm/venv/urllib3/connection.py", line 441, in request
    self.endheaders()
  File "/usr/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/usr/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/var/lib/juju/agents/unit-postgresql-2/charm/venv/urllib3/connection.py", line 279, in connect
    self.sock = self._new_conn()
  File "/var/lib/juju/agents/unit-postgresql-2/charm/venv/urllib3/connection.py", line 214, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f8d5bf612a0>: Failed to establish a new connection: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-2/charm/venv/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
  File "/var/lib/juju/agents/unit-postgresql-2/charm/venv/urllib3/connectionpool.py", line 843, in urlopen
    retries = retries.increment(
  File "/var/lib/juju/agents/unit-postgresql-2/charm/venv/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='10.120.111.230', port=8008): Max retries exceeded with url: /cluster (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8d5bf612a0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-2/charm/src/cluster.py", line 531, in are_replicas_up
    response = requests.get(
  File "/var/lib/juju/agents/unit-postgresql-2/charm/venv/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/var/lib/juju/agents/unit-postgresql-2/charm/venv/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/var/lib/juju/agents/unit-postgresql-2/charm/venv/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/var/lib/juju/agents/unit-postgresql-2/charm/venv/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/var/lib/juju/agents/unit-postgresql-2/charm/venv/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='10.120.111.230', port=8008): Max retries exceeded with url: /cluster (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8d5bf612a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-pgbouncer-1: 01:53:43 ERROR unit.pgbouncer/1.juju-log backend-database:7: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-pgbouncer-1/charm/venv/ops/model.py", line 3320, in _run
    result = subprocess.run(args, **kwargs)  # type: ignore
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('/var/lib/juju/tools/unit-pgbouncer-1/secret-get', '--label', 'pgb-peers.pgbouncer.app', '--format=json')' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-pgbouncer-1/charm/./src/charm.py", line 990, in <module>
    main(PgBouncerCharm)
  File "/var/lib/juju/agents/unit-pgbouncer-1/charm/venv/ops/__init__.py", line 343, in __call__
    return _main.main(charm_class=charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-pgbouncer-1/charm/venv/ops/_main.py", line 543, in main
    manager.run()
  File "/var/lib/juju/agents/unit-pgbouncer-1/charm/venv/ops/_main.py", line 529, in run
    self._emit()
  File "/var/lib/juju/agents/unit-pgbouncer-1/charm/venv/ops/_main.py", line 518, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name, self._juju_context)
  File "/var/lib/juju/agents/unit-pgbouncer-1/charm/venv/ops/_main.py", line 134, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-pgbouncer-1/charm/venv/ops/framework.py", line 347, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-pgbouncer-1/charm/venv/ops/framework.py", line 857, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-pgbouncer-1/charm/venv/ops/framework.py", line 947, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-pgbouncer-1/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 1064, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-pgbouncer-1/charm/src/relations/backend_database.py", line 238, in _on_relation_changed
    self.charm.render_pgb_config(reload_pgbouncer=True)
  File "/var/lib/juju/agents/unit-pgbouncer-1/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 1064, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-pgbouncer-1/charm/./src/charm.py", line 806, in render_pgb_config
    databases = self._get_relation_config()
  File "/var/lib/juju/agents/unit-pgbouncer-1/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 1064, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-pgbouncer-1/charm/./src/charm.py", line 718, in _get_relation_config
    if not self.backend.relation or not (databases := self.get_relation_databases()):
  File "/var/lib/juju/agents/unit-pgbouncer-1/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 1064, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-pgbouncer-1/charm/./src/charm.py", line 654, in get_relation_databases
    cfg := self.get_secret(APP_SCOPE, CFG_FILE_DATABAG_KEY)
  File "/var/lib/juju/agents/unit-pgbouncer-1/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 1064, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-pgbouncer-1/charm/./src/charm.py", line 319, in get_secret
    result := self.peer_relation_data(scope).fetch_my_relation_field(peers.id, key)
  File "/var/lib/juju/agents/unit-pgbouncer-1/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 1397, in fetch_my_relation_field
    if relation_data := self.fetch_my_relation_data([relation_id], [field], relation_name):
  File "/var/lib/juju/agents/unit-pgbouncer-1/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 1386, in fetch_my_relation_data
    data[relation.id] = self._fetch_my_specific_relation_data(relation, fields)
  File "/var/lib/juju/agents/unit-pgbouncer-1/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 536, in wrapper
    return f(self, *args, **kwargs)
  File "/var/lib/juju/agents/unit-pgbouncer-1/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 2344, in _fetch_my_specific_relation_data
    self.component, self.secret_fields, relation, fields
  File "/var/lib/juju/agents/unit-pgbouncer-1/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 1981, in secret_fields
    self.static_secret_fields if self.static_secret_fields else self.current_secret_fields
  File "/var/lib/juju/agents/unit-pgbouncer-1/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 2000, in current_secret_fields
    if content := self._get_group_secret_contents(relation, group):
  File "/var/lib/juju/agents/unit-pgbouncer-1/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 2331, in _get_group_secret_contents
    result = super()._get_group_secret_contents(relation, group, secret_fields)
  File "/var/lib/juju/agents/unit-pgbouncer-1/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 1123, in _get_group_secret_contents
    if (secret := self._get_relation_secret(relation.id, group)) and (
  File "/var/lib/juju/agents/unit-pgbouncer-1/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 508, in wrapper
    return f(self, *args, **kwargs)
  File "/var/lib/juju/agents/unit-pgbouncer-1/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 2318, in _get_relation_secret
    return self.secrets.get(
  File "/var/lib/juju/agents/unit-pgbouncer-1/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 812, in get
    if secret.meta:
  File "/var/lib/juju/agents/unit-pgbouncer-1/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 642, in meta
    self._secret_meta = self._model.get_secret(label=self.label)
  File "/var/lib/juju/agents/unit-pgbouncer-1/charm/venv/ops/model.py", line 308, in get_secret
    content = self._backend.secret_get(id=id, label=label)
  File "/var/lib/juju/agents/unit-pgbouncer-1/charm/venv/ops/model.py", line 3692, in secret_get
    result = self._run('secret-get', *args, return_output=True, use_json=True)
  File "/var/lib/juju/agents/unit-pgbouncer-1/charm/venv/ops/model.py", line 3322, in _run
    raise ModelError(e.stderr) from e
ops.model.ModelError: ERROR permission denied

unit-pgbouncer-1: 01:53:43 ERROR juju.worker.uniter.operation hook "backend-database-relation-changed" (via hook dispatching script: dispatch) failed: exit status 1

[32mINFO    [0m pytest_operator.plugin:plugin.py:1017 Forgetting model main...