[32mINFO    [0m root:helpers.py:96 (0, '{"pgbouncer/5":{"workload-version":"1.21.0","machine":"3","opened-ports":null,"public-address":"10.76.185.118","charm":"local:jammy/pgbouncer-0","leader":true,"life":"alive","relation-info":[{"relation-id":6,"endpoint":"backend-database","related-endpoint":"database","application-data":{"data":"{\\"database\\": \\"pgbouncer\\", \\"extra-user-roles\\": \\"SUPERUSER\\", \\"requested-secrets\\": \\"[\\\\\\"username\\\\\\", \\\\\\"password\\\\\\", \\\\\\"tls\\\\\\", \\\\\\"tls-ca\\\\\\", \\\\\\"uris\\\\\\"]\\"}","database":"pgbouncer","endpoints":"10.76.185.89:5432","read-only-endpoints":"10.76.185.238:5432","secret-tls":"secret://1cf92fa3-8566-4e78-8388-47d2b2d06655/ctdp3tq6h361idfhk0s0","secret-user":"secret://1cf92fa3-8566-4e78-8388-47d2b2d06655/ctdp3tq6h361idfhk0rg","version":"14.13"},"local-unit":{"in-scope":false,"data":null},"related-units":{"postgresql/0":{"in-scope":true,"data":{"egress-subnets":"10.76.185.238/32","ingress-address":"10.76.185.238","private-address":"10.76.185.238"}},"postgresql/1":{"in-scope":true,"data":{"egress-subnets":"10.76.185.89/32","ingress-address":"10.76.185.89","private-address":"10.76.185.89"}}}},{"relation-id":17,"endpoint":"database","related-endpoint":"database","application-data":{"database":"postgresql_test_app_database","extra-user-roles":"CREATEDB,CREATEROLE","requested-secrets":"[\\"username\\", \\"password\\", \\"tls\\", \\"tls-ca\\", \\"uris\\"]"},"local-unit":{"in-scope":false,"data":null},"related-units":{"postgresql-test-app/1":{"in-scope":true,"data":{"data":"{\\"database\\": \\"postgresql_test_app_database\\", \\"endpoints\\": \\"localhost:6432\\", \\"secret-user\\": \\"secret://1cf92fa3-8566-4e78-8388-47d2b2d06655/ctdpdv26h361idfhk110\\", \\"subordinated\\": \\"true\\", \\"version\\": \\"14.13\\"}","egress-subnets":"10.76.185.118/32","ingress-address":"10.76.185.118","private-address":"10.76.185.118"}},"postgresql-test-app/2":{"in-scope":true,"data":{"data":"{\\"database\\": \\"postgresql_test_app_database\\", \\"endpoints\\": \\"localhost:6432\\", \\"secret-user\\": \\"secret://1cf92fa3-8566-4e78-8388-47d2b2d06655/ctdpdv26h361idfhk110\\", \\"subordinated\\": \\"true\\", \\"version\\": \\"14.13\\"}","egress-subnets":"10.76.185.97/32","ingress-address":"10.76.185.97","private-address":"10.76.185.97"}}}},{"relation-id":5,"endpoint":"pgb-peers","related-endpoint":"pgb-peers","application-data":{"current_port":"6432","leader_ip":"10.76.185.118","pgb_dbs_config":"{\\"17\\": {\\"name\\": \\"postgresql_test_app_database\\", \\"legacy\\": false}, \\"*\\": {\\"name\\": \\"*\\", \\"auth_dbname\\": \\"postgresql_test_app_database\\"}}","readonly_dbs":"[\\"another_database\\", \\"postgresql_test_app_multiple_database_clusters\\"]"},"local-unit":{"in-scope":true,"data":{"auth_file_set":"true","egress-subnets":"10.76.185.118/32","ingress-address":"10.76.185.118","pgb_dbs":"3f7f43cebb47d7003b9dfaa7213fd98c","private-address":"10.76.185.118"}},"related-units":{"pgbouncer/10":{"in-scope":true,"data":{"auth_file_set":"true","egress-subnets":"10.76.185.97/32","ingress-address":"10.76.185.97","pgb_dbs":"3f7f43cebb47d7003b9dfaa7213fd98c","private-address":"10.76.185.97"}}}},{"relation-id":4,"endpoint":"upgrade","related-endpoint":"upgrade","application-data":{"dependencies":"{\\"charm\\": {\\"dependencies\\": {}, \\"name\\": \\"pgbouncer\\", \\"upgrade_supported\\": \\"\\u003e0\\", \\"version\\": \\"1\\"}, \\"snap\\": {\\"dependencies\\": {}, \\"name\\": \\"charmed-postgresql\\", \\"upgrade_supported\\": \\"^1\\", \\"version\\": \\"1.18.0\\"}}"},"local-unit":{"in-scope":true,"data":{"egress-subnets":"10.76.185.118/32","ingress-address":"10.76.185.118","private-address":"10.76.185.118","state":"idle"}},"related-units":{"pgbouncer/10":{"in-scope":true,"data":{"egress-subnets":"10.76.185.97/32","ingress-address":"10.76.185.97","private-address":"10.76.185.97","state":"idle"}}}}]}}\n', '')
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  postgresql-test-app/1 [executing] active: received database credentials of the first database
  postgresql-test-app/2 [executing] active: received database credentials of the second database
  postgresql/0 [executing] active: 
  postgresql/1 [executing] active: Primary
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  postgresql-test-app/2 [idle] active:
[32mINFO    [0m pytest_operator.plugin:plugin.py:929 Model status:

Model  Controller           Cloud/Region         Version  SLA          Timestamp
test   localhost-localhost  localhost/localhost  3.4.6    unsupported  02:14:47Z

App                  Version  Status   Scale  Charm                Channel      Rev  Exposed  Message
another-application           active       1  postgresql-test-app  latest/edge  299  no       
another-pgbouncer    1.21.0   active       2  pgbouncer                           1  no       
another-postgresql   14.13    active       2  postgresql           14/edge      532  no       
pgbouncer                     unknown      0  pgbouncer                           0  no       
postgresql           14.13    active       2  postgresql           14/edge      532  no       
postgresql-test-app           active       2  postgresql-test-app  latest/edge  299  no       

Unit                    Workload  Agent  Machine  Public address  Ports     Message
another-application/0*  active    idle   4        10.76.185.79              
another-postgresql/0*   active    idle   5        10.76.185.218   5432/tcp  Primary
another-postgresql/1    active    idle   6        10.76.185.56    5432/tcp  
postgresql-test-app/1*  active    idle   3        10.76.185.118             
  another-pgbouncer/3*  active    idle            10.76.185.118             
postgresql-test-app/2   active    idle   7        10.76.185.97              
  another-pgbouncer/6   active    idle            10.76.185.97              
postgresql/0            active    idle   1        10.76.185.238   5432/tcp  
postgresql/1*           active    idle   2        10.76.185.89    5432/tcp  Primary

Machine  State    Address        Inst id        Base          AZ  Message
1        started  10.76.185.238  juju-d06655-1  ubuntu@22.04      Running
2        started  10.76.185.89   juju-d06655-2  ubuntu@22.04      Running
3        started  10.76.185.118  juju-d06655-3  ubuntu@22.04      Running
4        started  10.76.185.79   juju-d06655-4  ubuntu@22.04      Running
5        started  10.76.185.218  juju-d06655-5  ubuntu@22.04      Running
6        started  10.76.185.56   juju-d06655-6  ubuntu@22.04      Running
7        started  10.76.185.97   juju-d06655-7  ubuntu@22.04      Running

[32mINFO    [0m pytest_operator.plugin:plugin.py:935 Juju error logs:

machine-2: 01:43:01 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-2: 01:43:01 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-postgresql-1: 01:43:01 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-1: 01:43:05 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-1: 01:43:05 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-postgresql-0: 01:43:05 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-0: 01:43:07 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-0: 01:43:07 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-postgresql-test-app-0: 01:43:08 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-postgresql-1: 01:43:57 ERROR unit.postgresql/1.juju-log Unable to get the state of the cluster
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/urllib3/connection.py", line 199, in _new_conn
    sock = connection.create_connection(
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/urllib3/connectionpool.py", line 495, in _make_request
    conn.request(
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/urllib3/connection.py", line 441, in request
    self.endheaders()
  File "/usr/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/usr/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/urllib3/connection.py", line 279, in connect
    self.sock = self._new_conn()
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/urllib3/connection.py", line 214, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f13417611b0>: Failed to establish a new connection: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/urllib3/connectionpool.py", line 843, in urlopen
    retries = retries.increment(
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='10.76.185.89', port=8008): Max retries exceeded with url: /cluster (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f13417611b0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-1/charm/src/cluster.py", line 531, in are_replicas_up
    response = requests.get(
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='10.76.185.89', port=8008): Max retries exceeded with url: /cluster (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f13417611b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-pgbouncer-0: 01:46:12 ERROR juju.worker.meterstatus error running "meter-status-changed": exit status 1
machine-3: 01:52:03 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-3: 01:52:03 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-postgresql-test-app-1: 01:52:03 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-pgbouncer-1: 01:52:07 ERROR juju.worker.meterstatus error running "meter-status-changed": exit status 1
machine-4: 01:54:49 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-4: 01:54:49 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-another-application-0: 01:54:49 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-pgbouncer-1: 01:55:42 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: relation scope id "1cf92fa3-8566-4e78-8388-47d2b2d06655:r#7#postgresql-test-app": settings 1cf92fa3-8566-4e78-8388-47d2b2d06655:r#7#postgresql-test-app not found (not found)
unit-postgresql-test-app-1: 01:55:42 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: relation scope id "1cf92fa3-8566-4e78-8388-47d2b2d06655:r#7#pgbouncer": settings 1cf92fa3-8566-4e78-8388-47d2b2d06655:r#7#pgbouncer not found (not found)
machine-5: 01:57:45 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-5: 01:57:45 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-another-postgresql-0: 01:57:45 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-6: 01:57:48 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-6: 01:57:48 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-another-postgresql-1: 01:57:48 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-another-postgresql-0: 01:58:52 ERROR unit.another-postgresql/0.juju-log Unable to get the state of the cluster
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-another-postgresql-0/charm/venv/urllib3/connection.py", line 199, in _new_conn
    sock = connection.create_connection(
  File "/var/lib/juju/agents/unit-another-postgresql-0/charm/venv/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/var/lib/juju/agents/unit-another-postgresql-0/charm/venv/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-another-postgresql-0/charm/venv/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
  File "/var/lib/juju/agents/unit-another-postgresql-0/charm/venv/urllib3/connectionpool.py", line 495, in _make_request
    conn.request(
  File "/var/lib/juju/agents/unit-another-postgresql-0/charm/venv/urllib3/connection.py", line 441, in request
    self.endheaders()
  File "/usr/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/usr/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/var/lib/juju/agents/unit-another-postgresql-0/charm/venv/urllib3/connection.py", line 279, in connect
    self.sock = self._new_conn()
  File "/var/lib/juju/agents/unit-another-postgresql-0/charm/venv/urllib3/connection.py", line 214, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f53360e0dc0>: Failed to establish a new connection: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-another-postgresql-0/charm/venv/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
  File "/var/lib/juju/agents/unit-another-postgresql-0/charm/venv/urllib3/connectionpool.py", line 843, in urlopen
    retries = retries.increment(
  File "/var/lib/juju/agents/unit-another-postgresql-0/charm/venv/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='10.76.185.218', port=8008): Max retries exceeded with url: /cluster (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f53360e0dc0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-another-postgresql-0/charm/src/cluster.py", line 531, in are_replicas_up
    response = requests.get(
  File "/var/lib/juju/agents/unit-another-postgresql-0/charm/venv/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/var/lib/juju/agents/unit-another-postgresql-0/charm/venv/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/var/lib/juju/agents/unit-another-postgresql-0/charm/venv/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/var/lib/juju/agents/unit-another-postgresql-0/charm/venv/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/var/lib/juju/agents/unit-another-postgresql-0/charm/venv/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='10.76.185.218', port=8008): Max retries exceeded with url: /cluster (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f53360e0dc0>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-pgbouncer-3: 02:04:54 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-pgbouncer-2: 02:04:54 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-another-pgbouncer-0: 02:04:55 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-another-pgbouncer-1: 02:04:55 ERROR juju.worker.meterstatus error running "meter-status-changed": exit status 126
machine-3: 02:06:54 ERROR juju.api.watcher error trying to stop watcher: websocket: close sent
unit-pgbouncer-5: 02:07:00 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-pgbouncer-4: 02:07:00 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-another-pgbouncer-3: 02:07:02 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-another-pgbouncer-2: 02:07:02 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-0: 02:09:30 ERROR juju.api.watcher error trying to stop watcher: websocket: close sent
machine-7: 02:12:16 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-7: 02:12:16 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-postgresql-test-app-2: 02:12:16 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-pgbouncer-10: 02:12:19 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-another-pgbouncer-6: 02:12:20 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-postgresql-test-app-2: 02:14:07 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: relation scope id "1cf92fa3-8566-4e78-8388-47d2b2d06655:r#17#pgbouncer": settings 1cf92fa3-8566-4e78-8388-47d2b2d06655:r#17#pgbouncer not found (not found)

[32mINFO    [0m pytest_operator.plugin:plugin.py:1017 Forgetting model main...