[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  postgresql-test-app (waiting for exactly 3 units, current : 4)
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  postgresql-test-app (waiting for exactly 3 units, current : 4)
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  postgresql-test-app/1 [idle] active: received database credentials of the first database
  postgresql-test-app/2 [idle] active: received database credentials of the first database
  postgresql-test-app/3 [idle] active: received database credentials of the first database
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  landscape-client/0 [idle] active: Client registered!
  landscape-client/1 [idle] active: Client registered!
  landscape-client/4 [idle] active: Client registered!
  landscape-client/6 [idle] active: Client registered!
  landscape-client/7 [idle] active: Client registered!
  landscape-client/8 [idle] active: Client registered!
  ubuntu-advantage/0 [idle] active: Attached (esm-apps,esm-infra)
  ubuntu-advantage/1 [idle] active: Attached (esm-apps,esm-infra)
  ubuntu-advantage/2 [idle] active: Attached (esm-apps,esm-infra)
  ubuntu-advantage/4 [idle] active: Attached (esm-apps,esm-infra)
  ubuntu-advantage/5 [idle] active: Attached (esm-apps,esm-infra)
  ubuntu-advantage/6 [idle] active: Attached (esm-apps,esm-infra)
  postgresql-test-app/1 [idle] active: received database credentials of the first database
  postgresql-test-app/2 [idle] active: received database credentials of the first database
  postgresql-test-app/3 [idle] active: received database credentials of the first database
  postgresql/0 [idle] active: Primary
  postgresql/1 [idle] active: 
  postgresql/2 [idle] active: 
  pgbouncer/1 [idle] active: 
  pgbouncer/2 [idle] active: 
  pgbouncer/3 [idle] active:
[32mINFO    [0m pytest_operator.plugin:plugin.py:936 Model status:

Model    Controller     Cloud/Region         Version  SLA          Timestamp
testing  concierge-lxd  localhost/localhost  3.6.3    unsupported  02:00:27Z

App                  Version  Status  Scale  Charm                Channel      Rev  Exposed  Message
landscape-client              active      6  landscape-client     latest/edge   71  no       Client registered!
pgbouncer            1.21.0   active      3  pgbouncer                           0  no       
postgresql           14.15    active      3  postgresql           14/edge      570  no       
postgresql-test-app           active      3  postgresql-test-app  latest/edge  367  no       received database credentials of the first database
ubuntu-advantage              active      6  ubuntu-advantage     latest/edge  137  no       Attached (esm-apps,esm-infra)

Unit                    Workload  Agent  Machine  Public address  Ports     Message
postgresql-test-app/1*  active    idle   1        10.110.235.146            received database credentials of the first database
  landscape-client/0    active    idle            10.110.235.146            Client registered!
  pgbouncer/1*          active    idle            10.110.235.146            
  ubuntu-advantage/0    active    idle            10.110.235.146            Attached (esm-apps,esm-infra)
postgresql-test-app/2   active    idle   2        10.110.235.71             received database credentials of the first database
  landscape-client/1*   active    idle            10.110.235.71             Client registered!
  pgbouncer/2           active    idle            10.110.235.71             
  ubuntu-advantage/1    active    idle            10.110.235.71             Attached (esm-apps,esm-infra)
postgresql-test-app/3   active    idle   6        10.110.235.211            received database credentials of the first database
  landscape-client/8    active    idle            10.110.235.211            Client registered!
  pgbouncer/3           active    idle            10.110.235.211            
  ubuntu-advantage/6    active    idle            10.110.235.211            Attached (esm-apps,esm-infra)
postgresql/0*           active    idle   3        10.110.235.181  5432/tcp  Primary
  landscape-client/7    active    idle            10.110.235.181            Client registered!
  ubuntu-advantage/5    active    idle            10.110.235.181            Attached (esm-apps,esm-infra)
postgresql/1            active    idle   4        10.110.235.244  5432/tcp  
  landscape-client/6    active    idle            10.110.235.244            Client registered!
  ubuntu-advantage/4    active    idle            10.110.235.244            Attached (esm-apps,esm-infra)
postgresql/2            active    idle   5        10.110.235.231  5432/tcp  
  landscape-client/4    active    idle            10.110.235.231            Client registered!
  ubuntu-advantage/2*   active    idle            10.110.235.231            Attached (esm-apps,esm-infra)

Machine  State    Address         Inst id        Base          AZ  Message
1        started  10.110.235.146  juju-433c75-1  ubuntu@22.04      Running
2        started  10.110.235.71   juju-433c75-2  ubuntu@22.04      Running
3        started  10.110.235.181  juju-433c75-3  ubuntu@22.04      Running
4        started  10.110.235.244  juju-433c75-4  ubuntu@22.04      Running
5        started  10.110.235.231  juju-433c75-5  ubuntu@22.04      Running
6        started  10.110.235.211  juju-433c75-6  ubuntu@22.04      Running

[32mINFO    [0m pytest_operator.plugin:plugin.py:942 Juju error logs:

machine-0: 01:41:05 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-0: 01:41:05 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-postgresql-test-app-0: 01:41:05 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-pgbouncer-0: 01:41:07 ERROR juju.worker.meterstatus error running "meter-status-changed": exit status 1
machine-3: 01:43:39 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-3: 01:43:39 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-postgresql-0: 01:43:41 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-5: 01:44:08 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-5: 01:44:08 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-postgresql-2: 01:44:08 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-4: 01:44:30 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-4: 01:44:30 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-postgresql-1: 01:44:30 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-1: 01:44:50 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-1: 01:44:50 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-postgresql-test-app-1: 01:44:50 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-pgbouncer-1: 01:44:55 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-postgresql-0: 01:45:11 ERROR unit.postgresql/0.juju-log Unable to get the state of the cluster
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/lib/python3.10/site-packages/urllib3/connection.py", line 198, in _new_conn
    sock = connection.create_connection(
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/lib/python3.10/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 493, in _make_request
    conn.request(
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/lib/python3.10/site-packages/urllib3/connection.py", line 445, in request
    self.endheaders()
  File "/usr/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/usr/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/lib/python3.10/site-packages/urllib3/connection.py", line 276, in connect
    self.sock = self._new_conn()
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/lib/python3.10/site-packages/urllib3/connection.py", line 213, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f33df3d06a0>: Failed to establish a new connection: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/lib/python3.10/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 841, in urlopen
    retries = retries.increment(
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/lib/python3.10/site-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='10.110.235.181', port=8008): Max retries exceeded with url: /cluster (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f33df3d06a0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-0/charm/src/cluster.py", line 552, in are_replicas_up
    response = requests.get(
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/lib/python3.10/site-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='10.110.235.181', port=8008): Max retries exceeded with url: /cluster (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f33df3d06a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
machine-2: 01:45:19 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-2: 01:45:19 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-postgresql-test-app-2: 01:45:20 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-pgbouncer-2: 01:45:25 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-landscape-client-1: 01:50:04 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-landscape-client-0: 01:50:04 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-landscape-client-4: 01:50:04 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-landscape-client-6: 01:50:04 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-landscape-client-3: 01:50:04 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-landscape-client-7: 01:50:08 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-ubuntu-advantage-5: 01:50:09 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-ubuntu-advantage-1: 01:50:42 ERROR unit.unit-ubuntu-advantage-1.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-ubuntu-advantage-1/charm/venv/ops/model.py", line 2183, in _run
    result = run(args, **kwargs)
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('/var/lib/juju/tools/unit-ubuntu-advantage-1/config-get', '--format=json')' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-ubuntu-advantage-1/charm/./src/charm.py", line 427, in <module>
    main(UbuntuAdvantageCharm)
  File "/var/lib/juju/agents/unit-ubuntu-advantage-1/charm/venv/ops/main.py", line 426, in main
    charm = charm_class(framework)
  File "/var/lib/juju/agents/unit-ubuntu-advantage-1/charm/./src/charm.py", line 233, in __init__
    self._setup_proxy_env()
  File "/var/lib/juju/agents/unit-ubuntu-advantage-1/charm/./src/charm.py", line 249, in _setup_proxy_env
    self.proxy_env["http_proxy"] = self.config.get(
  File "/usr/lib/python3.10/_collections_abc.py", line 824, in get
    return self[key]
  File "/var/lib/juju/agents/unit-ubuntu-advantage-1/charm/venv/ops/model.py", line 547, in __getitem__
    return self._data[key]
  File "/var/lib/juju/agents/unit-ubuntu-advantage-1/charm/venv/ops/model.py", line 531, in _data
    data = self._lazy_data = self._load()
  File "/var/lib/juju/agents/unit-ubuntu-advantage-1/charm/venv/ops/model.py", line 1092, in _load
    return self._backend.config_get()
  File "/var/lib/juju/agents/unit-ubuntu-advantage-1/charm/venv/ops/model.py", line 2299, in config_get
    out = self._run('config-get', return_output=True, use_json=True)
  File "/var/lib/juju/agents/unit-ubuntu-advantage-1/charm/venv/ops/model.py", line 2189, in _run
    raise ModelError(e.stderr)
ops.model.ModelError: b'ERROR not implemented for restricted context not implemented\n'
unit-ubuntu-advantage-3: 01:50:42 ERROR unit.unit-ubuntu-advantage-3.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-ubuntu-advantage-3/charm/venv/ops/model.py", line 2183, in _run
    result = run(args, **kwargs)
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('/var/lib/juju/tools/unit-ubuntu-advantage-3/config-get', '--format=json')' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-ubuntu-advantage-3/charm/./src/charm.py", line 427, in <module>
    main(UbuntuAdvantageCharm)
  File "/var/lib/juju/agents/unit-ubuntu-advantage-3/charm/venv/ops/main.py", line 426, in main
    charm = charm_class(framework)
  File "/var/lib/juju/agents/unit-ubuntu-advantage-3/charm/./src/charm.py", line 233, in __init__
    self._setup_proxy_env()
  File "/var/lib/juju/agents/unit-ubuntu-advantage-3/charm/./src/charm.py", line 249, in _setup_proxy_env
    self.proxy_env["http_proxy"] = self.config.get(
  File "/usr/lib/python3.10/_collections_abc.py", line 824, in get
    return self[key]
  File "/var/lib/juju/agents/unit-ubuntu-advantage-3/charm/venv/ops/model.py", line 547, in __getitem__
    return self._data[key]
  File "/var/lib/juju/agents/unit-ubuntu-advantage-3/charm/venv/ops/model.py", line 531, in _data
    data = self._lazy_data = self._load()
  File "/var/lib/juju/agents/unit-ubuntu-advantage-3/charm/venv/ops/model.py", line 1092, in _load
    return self._backend.config_get()
  File "/var/lib/juju/agents/unit-ubuntu-advantage-3/charm/venv/ops/model.py", line 2299, in config_get
    out = self._run('config-get', return_output=True, use_json=True)
  File "/var/lib/juju/agents/unit-ubuntu-advantage-3/charm/venv/ops/model.py", line 2189, in _run
    raise ModelError(e.stderr)
ops.model.ModelError: b'ERROR not implemented for restricted context not implemented\n'
unit-ubuntu-advantage-1: 01:50:42 ERROR juju.worker.meterstatus error running "meter-status-changed": exit status 1
unit-ubuntu-advantage-3: 01:50:42 ERROR juju.worker.meterstatus error running "meter-status-changed": exit status 1
unit-ubuntu-advantage-0: 01:50:43 ERROR unit.unit-ubuntu-advantage-0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-ubuntu-advantage-0/charm/venv/ops/model.py", line 2183, in _run
    result = run(args, **kwargs)
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('/var/lib/juju/tools/unit-ubuntu-advantage-0/config-get', '--format=json')' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-ubuntu-advantage-0/charm/./src/charm.py", line 427, in <module>
    main(UbuntuAdvantageCharm)
  File "/var/lib/juju/agents/unit-ubuntu-advantage-0/charm/venv/ops/main.py", line 426, in main
    charm = charm_class(framework)
  File "/var/lib/juju/agents/unit-ubuntu-advantage-0/charm/./src/charm.py", line 233, in __init__
    self._setup_proxy_env()
  File "/var/lib/juju/agents/unit-ubuntu-advantage-0/charm/./src/charm.py", line 249, in _setup_proxy_env
    self.proxy_env["http_proxy"] = self.config.get(
  File "/usr/lib/python3.10/_collections_abc.py", line 824, in get
    return self[key]
  File "/var/lib/juju/agents/unit-ubuntu-advantage-0/charm/venv/ops/model.py", line 547, in __getitem__
    return self._data[key]
  File "/var/lib/juju/agents/unit-ubuntu-advantage-0/charm/venv/ops/model.py", line 531, in _data
    data = self._lazy_data = self._load()
  File "/var/lib/juju/agents/unit-ubuntu-advantage-0/charm/venv/ops/model.py", line 1092, in _load
    return self._backend.config_get()
  File "/var/lib/juju/agents/unit-ubuntu-advantage-0/charm/venv/ops/model.py", line 2299, in config_get
    out = self._run('config-get', return_output=True, use_json=True)
  File "/var/lib/juju/agents/unit-ubuntu-advantage-0/charm/venv/ops/model.py", line 2189, in _run
    raise ModelError(e.stderr)
ops.model.ModelError: b'ERROR not implemented for restricted context not implemented\n'
unit-ubuntu-advantage-0: 01:50:43 ERROR juju.worker.meterstatus error running "meter-status-changed": exit status 1
unit-ubuntu-advantage-4: 01:50:44 ERROR unit.unit-ubuntu-advantage-4.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-ubuntu-advantage-4/charm/venv/ops/model.py", line 2183, in _run
    result = run(args, **kwargs)
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('/var/lib/juju/tools/unit-ubuntu-advantage-4/config-get', '--format=json')' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-ubuntu-advantage-4/charm/./src/charm.py", line 427, in <module>
    main(UbuntuAdvantageCharm)
  File "/var/lib/juju/agents/unit-ubuntu-advantage-4/charm/venv/ops/main.py", line 426, in main
    charm = charm_class(framework)
  File "/var/lib/juju/agents/unit-ubuntu-advantage-4/charm/./src/charm.py", line 233, in __init__
    self._setup_proxy_env()
  File "/var/lib/juju/agents/unit-ubuntu-advantage-4/charm/./src/charm.py", line 249, in _setup_proxy_env
    self.proxy_env["http_proxy"] = self.config.get(
  File "/usr/lib/python3.10/_collections_abc.py", line 824, in get
    return self[key]
  File "/var/lib/juju/agents/unit-ubuntu-advantage-4/charm/venv/ops/model.py", line 547, in __getitem__
    return self._data[key]
  File "/var/lib/juju/agents/unit-ubuntu-advantage-4/charm/venv/ops/model.py", line 531, in _data
    data = self._lazy_data = self._load()
  File "/var/lib/juju/agents/unit-ubuntu-advantage-4/charm/venv/ops/model.py", line 1092, in _load
    return self._backend.config_get()
  File "/var/lib/juju/agents/unit-ubuntu-advantage-4/charm/venv/ops/model.py", line 2299, in config_get
    out = self._run('config-get', return_output=True, use_json=True)
  File "/var/lib/juju/agents/unit-ubuntu-advantage-4/charm/venv/ops/model.py", line 2189, in _run
    raise ModelError(e.stderr)
ops.model.ModelError: b'ERROR not implemented for restricted context not implemented\n'
unit-ubuntu-advantage-4: 01:50:44 ERROR juju.worker.meterstatus error running "meter-status-changed": exit status 1
unit-ubuntu-advantage-2: 01:50:46 ERROR unit.unit-ubuntu-advantage-2.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-ubuntu-advantage-2/charm/venv/ops/model.py", line 2183, in _run
    result = run(args, **kwargs)
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('/var/lib/juju/tools/unit-ubuntu-advantage-2/config-get', '--format=json')' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-ubuntu-advantage-2/charm/./src/charm.py", line 427, in <module>
    main(UbuntuAdvantageCharm)
  File "/var/lib/juju/agents/unit-ubuntu-advantage-2/charm/venv/ops/main.py", line 426, in main
    charm = charm_class(framework)
  File "/var/lib/juju/agents/unit-ubuntu-advantage-2/charm/./src/charm.py", line 233, in __init__
    self._setup_proxy_env()
  File "/var/lib/juju/agents/unit-ubuntu-advantage-2/charm/./src/charm.py", line 249, in _setup_proxy_env
    self.proxy_env["http_proxy"] = self.config.get(
  File "/usr/lib/python3.10/_collections_abc.py", line 824, in get
    return self[key]
  File "/var/lib/juju/agents/unit-ubuntu-advantage-2/charm/venv/ops/model.py", line 547, in __getitem__
    return self._data[key]
  File "/var/lib/juju/agents/unit-ubuntu-advantage-2/charm/venv/ops/model.py", line 531, in _data
    data = self._lazy_data = self._load()
  File "/var/lib/juju/agents/unit-ubuntu-advantage-2/charm/venv/ops/model.py", line 1092, in _load
    return self._backend.config_get()
  File "/var/lib/juju/agents/unit-ubuntu-advantage-2/charm/venv/ops/model.py", line 2299, in config_get
    out = self._run('config-get', return_output=True, use_json=True)
  File "/var/lib/juju/agents/unit-ubuntu-advantage-2/charm/venv/ops/model.py", line 2189, in _run
    raise ModelError(e.stderr)
ops.model.ModelError: b'ERROR not implemented for restricted context not implemented\n'
unit-ubuntu-advantage-2: 01:50:46 ERROR juju.worker.meterstatus error running "meter-status-changed": exit status 1
machine-6: 01:55:52 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-6: 01:55:52 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-postgresql-test-app-3: 01:55:52 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-pgbouncer-3: 01:55:54 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-landscape-client-8: 01:55:55 ERROR juju.worker.meterstatus error running "meter-status-changed": exit status 1
unit-ubuntu-advantage-6: 01:55:55 ERROR juju.worker.meterstatus error running "meter-status-changed": exit status 127
unit-ubuntu-advantage-4: 01:59:51 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-postgresql-0: 01:59:51 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-ubuntu-advantage-1: 01:59:51 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-landscape-client-7: 01:59:52 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: write tcp 10.110.235.181:48010->10.110.235.154:17070: write: connection reset by peer: write tcp 10.110.235.181:48010->10.110.235.154:17070: write: connection reset by peer
unit-postgresql-test-app-1: 01:59:52 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-ubuntu-advantage-5: 01:59:52 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-postgresql-test-app-2: 01:59:53 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-landscape-client-4: 01:59:53 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: write tcp 10.110.235.231:59830->10.110.235.154:17070: write: connection reset by peer: write tcp 10.110.235.231:59830->10.110.235.154:17070: write: connection reset by peer
unit-landscape-client-6: 01:59:53 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-pgbouncer-1: 01:59:53 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-landscape-client-1: 01:59:53 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: write tcp 10.110.235.71:39712->10.110.235.154:17070: write: broken pipe: write tcp 10.110.235.71:39712->10.110.235.154:17070: write: broken pipe
unit-ubuntu-advantage-6: 01:59:54 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-postgresql-2: 01:59:54 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-landscape-client-8: 01:59:54 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-landscape-client-0: 01:59:54 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-pgbouncer-2: 01:59:55 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-pgbouncer-3: 01:59:55 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-postgresql-1: 01:59:56 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-postgresql-test-app-3: 01:59:57 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-ubuntu-advantage-2: 01:59:57 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-ubuntu-advantage-0: 01:59:57 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent

[32mINFO    [0m pytest_operator.plugin:plugin.py:1024 Forgetting model main...