[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  pgbouncer/0 [executing] active: VIP: 10.3.82.193
  pgbouncer/1 [executing] active: 
  pgbouncer/3 [executing] active: 
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  pgbouncer/0 [executing] maintenance: Reloading Pgbouncer
  pgbouncer/1 [executing] blocked: ha integration used without vip configuration
  pgbouncer/3 [idle] blocked: ha integration used without vip configuration
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  pgbouncer/0 [idle] blocked: ha integration used without vip configuration
  pgbouncer/1 [idle] blocked: ha integration used without vip configuration
  pgbouncer/3 [idle] blocked: ha integration used without vip configuration
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  pgbouncer/0 [executing] maintenance: Reloading Pgbouncer
  pgbouncer/1 [idle] active: 
  pgbouncer/3 [idle] active: 
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  pgbouncer/0 [idle] active: 
  pgbouncer/1 [idle] active: 
  pgbouncer/3 [idle] active: 
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  pgbouncer/0 [idle] active: 
  pgbouncer/1 [idle] active: 
  pgbouncer/3 [idle] active: 
[32mINFO    [0m integration.relations.pgbouncer_provider.test_data_integrator_ha:test_data_integrator_ha.py:150 Data integrator host is 10.3.82.118
[32mINFO    [0m pytest_operator.plugin:plugin.py:937 Model status:

Model    Controller     Cloud/Region         Version  SLA          Timestamp
testing  concierge-lxd  localhost/localhost  3.6.5    unsupported  02:00:44Z

App                       Version  Status  Scale  Charm                     Channel        Rev  Exposed  Message
data-integrator                    active      3  data-integrator           latest/edge    131  no       
hacluster                 2.1.2    active      3  hacluster                 2.4/stable     131  no       Unit is ready and clustered
pgbouncer                 1.21.0   active      3  pgbouncer                                  0  no       
postgresql                14.17    active      2  postgresql                14/edge        597  no       
self-signed-certificates           active      1  self-signed-certificates  latest/stable  264  no       

Unit                         Workload  Agent  Machine  Public address  Ports     Message
data-integrator/0            active    idle   0        10.3.82.192               
  hacluster/2                active    idle            10.3.82.192               Unit is ready and clustered
  pgbouncer/3                active    idle            10.3.82.192     6432/tcp  
data-integrator/1*           active    idle   1        10.3.82.217               
  hacluster/0*               active    idle            10.3.82.217               Unit is ready and clustered
  pgbouncer/1                active    idle            10.3.82.217     6432/tcp  
data-integrator/2            active    idle   2        10.3.82.118               
  hacluster/1                active    idle            10.3.82.118               Unit is ready and clustered
  pgbouncer/0*               active    idle            10.3.82.118     6432/tcp  
postgresql/0*                active    idle   4        10.3.82.253     5432/tcp  Primary
postgresql/1                 active    idle   5        10.3.82.129     5432/tcp  
self-signed-certificates/0*  active    idle   3        10.3.82.165               

Machine  State    Address      Inst id        Base          AZ  Message
0        started  10.3.82.192  juju-e118e3-0  ubuntu@22.04      Running
1        started  10.3.82.217  juju-e118e3-1  ubuntu@22.04      Running
2        started  10.3.82.118  juju-e118e3-2  ubuntu@22.04      Running
3        started  10.3.82.165  juju-e118e3-3  ubuntu@22.04      Running
4        started  10.3.82.253  juju-e118e3-4  ubuntu@22.04      Running
5        started  10.3.82.129  juju-e118e3-5  ubuntu@22.04      Running

[32mINFO    [0m pytest_operator.plugin:plugin.py:943 Juju error logs:

machine-1: 01:42:27 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-1: 01:42:27 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-data-integrator-1: 01:42:28 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-3: 01:45:04 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-3: 01:45:04 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-self-signed-certificates-0: 01:45:05 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-4: 01:45:26 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-4: 01:45:26 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-postgresql-0: 01:45:26 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-5: 01:45:45 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-5: 01:45:45 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-postgresql-1: 01:45:45 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-2: 01:46:02 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-2: 01:46:02 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-data-integrator-2: 01:46:02 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-0: 01:46:21 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-0: 01:46:21 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-data-integrator-0: 01:46:22 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-hacluster-2: 01:46:26 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-postgresql-0: 01:46:44 ERROR unit.postgresql/0.juju-log Unable to get the state of the cluster
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/lib/python3.10/site-packages/urllib3/connection.py", line 198, in _new_conn
    sock = connection.create_connection(
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/lib/python3.10/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 493, in _make_request
    conn.request(
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/lib/python3.10/site-packages/urllib3/connection.py", line 445, in request
    self.endheaders()
  File "/usr/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/usr/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/lib/python3.10/site-packages/urllib3/connection.py", line 276, in connect
    self.sock = self._new_conn()
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/lib/python3.10/site-packages/urllib3/connection.py", line 213, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fc1b2fba410>: Failed to establish a new connection: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/lib/python3.10/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 841, in urlopen
    retries = retries.increment(
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/lib/python3.10/site-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='10.3.82.253', port=8008): Max retries exceeded with url: /cluster (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc1b2fba410>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-0/charm/src/cluster.py", line 563, in are_replicas_up
    response = requests.get(
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/lib/python3.10/site-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='10.3.82.253', port=8008): Max retries exceeded with url: /cluster (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc1b2fba410>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-pgbouncer-0: 01:50:41 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-pgbouncer-1: 01:50:41 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-pgbouncer-3: 01:50:41 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-pgbouncer-3: 01:57:35 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: relation scope id "8eb513da-827c-4819-8d70-cf6c3ee118e3:r#11#self-signed-certificates": settings 8eb513da-827c-4819-8d70-cf6c3ee118e3:r#11#self-signed-certificates not found (not found)

[32mINFO    [0m pytest_operator.plugin:plugin.py:1025 Forgetting model main...