[32mINFO    [0m pytest_operator.plugin:plugin.py:903 Model status:

Model  Controller           Cloud/Region         Version  SLA          Timestamp
test   localhost-localhost  localhost/localhost  3.4.6    unsupported  02:08:26Z

App                  Version  Status   Scale  Charm                Channel      Rev  Exposed  Message
pgbouncer            1.21.0   blocked      3  pgbouncer                           0  no       waiting for backend database relation to initialise
postgresql           14.13    active       3  postgresql           14/edge      530  no       
postgresql-test-app           active       3  postgresql-test-app  latest/edge  293  no       

Unit                    Workload     Agent      Machine  Public address  Ports     Message
postgresql-test-app/0*  active       idle       0        10.45.85.184              
  pgbouncer/1           blocked      idle                10.45.85.184              waiting for backend database relation to initialise
postgresql-test-app/1   active       idle       1        10.45.85.18               
  pgbouncer/0*          blocked      idle                10.45.85.18               waiting for backend database relation to initialise
postgresql-test-app/2   active       idle       2        10.45.85.2                
  pgbouncer/2           blocked      idle                10.45.85.2                waiting for backend database relation to initialise
postgresql/0*           maintenance  executing  3        10.45.85.49     5432/tcp  reconfiguring cluster
postgresql/1            waiting      idle       4        10.45.85.209    5432/tcp  awaiting for cluster to start
postgresql/2            waiting      idle       5        10.45.85.102    5432/tcp  awaiting for cluster to start

Machine  State    Address       Inst id        Base          AZ  Message
0        started  10.45.85.184  juju-a0348b-0  ubuntu@22.04      Running
1        started  10.45.85.18   juju-a0348b-1  ubuntu@22.04      Running
2        started  10.45.85.2    juju-a0348b-2  ubuntu@22.04      Running
3        started  10.45.85.49   juju-a0348b-3  ubuntu@22.04      Running
4        started  10.45.85.209  juju-a0348b-4  ubuntu@22.04      Running
5        started  10.45.85.102  juju-a0348b-5  ubuntu@22.04      Running

[32mINFO    [0m pytest_operator.plugin:plugin.py:909 Juju error logs:

machine-1: 01:49:50 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-1: 01:49:50 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-0: 01:49:50 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-0: 01:49:50 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-postgresql-test-app-0: 01:49:50 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-postgresql-test-app-1: 01:49:50 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-2: 01:49:55 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-2: 01:49:55 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-postgresql-test-app-2: 01:49:55 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-pgbouncer-1: 01:49:55 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-pgbouncer-0: 01:49:55 ERROR juju.worker.meterstatus error running "meter-status-changed": exit status 1
unit-pgbouncer-2: 01:50:01 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-3: 01:58:33 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-3: 01:58:33 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-postgresql-0: 01:58:33 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-4: 01:59:29 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-4: 01:59:29 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-postgresql-1: 01:59:29 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-5: 02:03:31 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-5: 02:03:31 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-postgresql-2: 02:03:31 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-postgresql-0: 02:05:19 ERROR unit.postgresql/0.juju-log Unable to get the state of the cluster
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/urllib3/connection.py", line 199, in _new_conn
    sock = connection.create_connection(
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/urllib3/connectionpool.py", line 495, in _make_request
    conn.request(
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/urllib3/connection.py", line 441, in request
    self.endheaders()
  File "/usr/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/usr/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/urllib3/connection.py", line 279, in connect
    self.sock = self._new_conn()
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/urllib3/connection.py", line 214, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7ebb73fcd840>: Failed to establish a new connection: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/urllib3/connectionpool.py", line 843, in urlopen
    retries = retries.increment(
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='10.45.85.49', port=8008): Max retries exceeded with url: /cluster (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ebb73fcd840>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-0/charm/src/cluster.py", line 531, in are_replicas_up
    response = requests.get(
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='10.45.85.49', port=8008): Max retries exceeded with url: /cluster (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ebb73fcd840>: Failed to establish a new connection: [Errno 111] Connection refused'))

[32mINFO    [0m pytest_operator.plugin:plugin.py:991 Forgetting model main...